name: CI

on:
    push:

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
# This will ensure that only one commit will be running tests at a time on each PR.
concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@v2

            - name: Install npm dependencies
              run: yarn install --frozen-lockfile

            - name: Run prettier
              run: yarn run format-check

    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@v2

            - name: Install npm dependencies
              run: yarn install --frozen-lockfile

            - name: Run eslint
              run: yarn run eslint-check
